### ISSUE TITLE
Deterministic 0%

### ISSUE THREAD

**Issue by christianbundy** [elsehow/aaronson-oracle#4]
Are there any plans to circumvent the 2^5 "attacks" such as `ddddd ffffff d ffff dd fff d f d fff ddd ff`, which always yield a 0% prediction rate? Or is this project specifically aimed at implementing a 5-gram prediction with no enhancements?

I've been having fun with this, thanks!

**Comment by elsehow** [comment]
Nice "attack"! It would definitely be cool to prevent such things, but I hesitate to add one-off "patches" since they make the solution a little more complex, whereas now there's just one mechanism one can describe in a sentence, with no "special cases."

One idea might be to train on e.g. 5-grams *and* 2-grams, though I'd need to think through how that might work.

**Comment by christianbundy** [comment]
Sounds good to me. In case it's something you're interested in merging in the future, the fix would be to calculate the probability of a prediction rather than choosing the n-gram with the highest probability every time. For example, an n-gram with `{ f: 1000, d: 1 }` (99.90%) currently has the same probability of picking `f` as `{f: 1000, d: 999}` (50.02%). Also, comparing `m.f > m.d` will *always* choose `f` any time it encounters a case where `m.f` and `m.d` are equal.

``` js
function getProbability (event, complement) {
  var total = event + complement
  // never divide by zero
  if (total === 0)
    return 1/2
  return event / total
}

function predictNextLetter (fivegram) {
  var m = model[fivegram]
  var p = getProbability(m.f, m.d)
  if (p > Math.random())
    return 'f'
  return 'd'
}
```

Given the examples above, we get the following:

``` js
var m = {f: 1000, d: 1};
getProbability(m.f, m.d); // returns 0.9990
```

``` js
var m = {f: 1000, d: 999};
getProbability(m.f, m.d); // returns 0.5002
```

This also solves the problem of having it default to `f`, as `Math.random()` chooses a pseudo-random number between `0` and `0.9999999999999999`.

**Comment by elsehow** [comment]
Fantastic! Would you issue a PR for this?

**Comment by christianbundy** [comment]
Done!
