### ISSUE TITLE
Always guesses d first

### ISSUE THREAD

**Issue by OisinMoran** [elsehow/aaronson-oracle#5]
Is it a problem or intentional that it always guesses d first regardless of the first five letters entered?
Also if you hold down f forever* it seems to only get to 99% accuracy but holding down d gets to 100%

*more than 201 guesses

**Comment by elsehow** [comment]
It does always guess 'd' first, and yes, that will result in 100% and 99% in those two cases! We start with zero information (no corpus), so it just "guesses" 'd.'
